audio_play_sound(Shop_Dream,1,1)
audio_play_sound(snd_piano,1,1)
audio_play_sound(snd_piano,1,1)
audio_play_sound(Otherworld,1,1)
audio_play_sound(Mystic_Town,1,1)
audio_play_sound(Lava_Level,1,1)
audio_play_sound(Echoes,1,1)
audio_play_sound(Disturbing_Property,1,1)
audio_play_sound(Desolation,1,1)
audio_play_sound(Deep_in_the_Caverns,1,1)
audio_play_sound(Danger_On_The_Peaks,1,1)
audio_play_sound(Boss_Fight,1,1)
audio_play_sound(Love,1,1)

window_set_size(1280, 720)
surface_resize(application_surface, 1280, 720)
application_surface_draw_enable(true)

audio_sound_gain(Shop_Dream, 0, 0)
audio_sound_gain(snd_piano, 0, 0)
audio_sound_gain(Otherworld, 0, 0)
audio_sound_gain(Mystic_Town, 0, 0)
audio_sound_gain(Lava_Level, 0, 0)
audio_sound_gain(Echoes, 0, 0)
audio_sound_gain(Disturbing_Property, 0, 0)
audio_sound_gain(Desolation, 0, 0)
audio_sound_gain(Deep_in_the_Caverns, 0, 0)
audio_sound_gain(Danger_On_The_Peaks, 0, 0)
audio_sound_gain(Boss_Fight, 0, 0)
audio_sound_gain(Love, 0, 0)